### ISSUE TITLE
Issues when parsing for others

### ISSUE THREAD

**Issue by kristophergeou** [HelpChat/DeluxeMenus#71] opened 2024-02-28 12:01 UTC
Hey there @BlitzOffline i think a few of the changes you did in the last dev build #178 regarding the parsing broke the parseother and utils expansion when you are trying to parse placeholders for another person. cause this is how the placeholders appear now with the latest build:
![image](https://github.com/HelpChat/DeluxeMenus/assets/114158743/64c8130e-6b85-4ea3-be30-f1df2ea1c1aa)
I also tried to use the previous build #177 and this issue doesnt seem to happen
![image](https://github.com/HelpChat/DeluxeMenus/assets/114158743/ca2dec19-5291-4907-854f-8745344dc415)

**Comment by BlitzOffline** [comment] 2024-02-28 17:00
This is probably related to this fix: https://github.com/HelpChat/DeluxeMenus/pull/46

@kristophergeou can you please add `arguments_support_placeholders: true` to your menu, restart the server and see if the issue persists? Some changes were made to how placeholders and arguments interact and it might be related to that.

**Comment by kristophergeou** [comment] 2024-02-28 17:13
This is my menu 
```yml
menu_title: '            &l« ᴄʜᴇᴄᴋ »'
size: 45
open_command: check
register_command: true
arguments_support_placeholders: true
args:
- username
args_usage_message: "§x§d§6§8§d§6§a§lC§x§d§6§9§1§7§4§lh§x§d§6§9§5§7§e§le§x§d§6§9§9§8§8§lc§x§d§6§9§d§9§2§lk &8» &7/check <username>"
open_requirement: 
  minimum_requirements: 1
  stop_at_success: true
  requirements: 
    player_played_before: 
      type: string equals 
      input: "%parseother_{{player}}_{player_has_played_before}%"
      output: "yes"
      optional: true
    player_is_online: 
      type: string equals
      input: "%parseother_{{player}}_{player_online}%"
      output: "yes"
      optional: true
  deny_commands: 
  - '[message] &7[&3&l!&7] &7This user never joined the server!'
items: 
# Start - User
  'user':
    material: head-{username}
    model_data: 10000
    slot: 10
    display_name: '&8« %gradient2_style:bold,&#D68D6A,&#D69D92,Profile% &8»'
    lore: 
    - ''
    - '&#D68D6A• &7Username: &#D69D92{username} '
    - '&#D68D6A• &7Display Name: &#D69D92%utils_parseother:[{username}]_rosechat_nickname_fallback% '
    - '&#D68D6A• &7Discord: &#D69D92@%utils_parseother:[{username}]_discordsrv_user_name% '
    - '&#D68D6A• &7Online: &#D69D92%utils_parseother:[{username}]_player_online% '
# End - User
```
I did add the `arguments_support_placeholders: true` to the menu and this is the result i get: 
![image](https://github.com/HelpChat/DeluxeMenus/assets/114158743/6d4b4603-e88a-4f3f-9fbf-e677d2d7239c)
Regular placeholders like `%player_name%` `%vault_eco_balance%` work just fine but the parsing ones dont

**Comment by BlitzOffline** [comment] 2024-03-25 21:28
Hello @kristophergeou,

After testing the latest build, I was not able to replicate your issue. As you will be able to see from the screenshots below, both the `utils` expansion's placeholder and the `parseother` expansion's placeholder work.

![image](https://github.com/HelpChat/DeluxeMenus/assets/52609756/4ca33e7d-afdd-4b66-8f8c-da2ddaf18b55)
![image](https://github.com/HelpChat/DeluxeMenus/assets/52609756/ed65645a-ad17-442f-ab50-84d0c951852b)

Versions I am using:
DeluxeMenus: 1.14.1-DEV-178
PlaceholderAPI: 2.11.3
ParseOther: 2.0.0
Utils: 1.0.9

**Comment by kristophergeou** [comment] 2024-03-25 21:40
Hey @BlitzOffline the player expansion works fine, try with a different placeholders like vault

**Comment by BlitzOffline** [comment] 2024-03-26 16:59
After looking more into this issue, I have found the root cause. I am going to close this ticket and mark it as a duplicate of https://github.com/HelpChat/DeluxeMenus/issues/78

**Closed by BlitzOffline** 2024-03-26 16:59 UTC
