### ISSUE TITLE
Additions to the <chance>

### ISSUE THREAD

**Issue by kristophergeou** [HelpChat/DeluxeMenus#22] opened 2023-12-24 02:31 UTC
Right now with the chance, we know that it's only possible to execute a single action when an action is successful. But what if we could create multiple ones just by adding something like `<+++>` that could support a 2nd, 3rd... action too. So:
`[message] &7Hello y won <+++>  [console] eco give %player_name% 5000<chance=10>`
so basically when the chance is included, the plugin will also search for a `<+++>` and it will know that there is more that 1 actions that needs to be executed. Also i think the `<+++>` is very very rare to be used normally, and that's why it can be used as an identifier for multiple actions in chance.

**Comment by BlitzOffline** [comment] 2024-04-05 15:28
Closing this as a duplicate of https://github.com/HelpChat/DeluxeMenus/issues/34. I have mentioned the suggested fix there so it does not get lost.

**Closed by BlitzOffline** 2024-04-05 15:28 UTC
Labels: enhancement
