### ISSUE TITLE
add minimessage support in menus

### ISSUE THREAD

**Issue by hun1yy** [HelpChat/DeluxeMenus#72] opened 2024-02-28 18:34 UTC
see title :)

**Comment by BlitzOffline** [comment] 2024-02-28 19:39
duplicate of https://github.com/HelpChat/DeluxeMenus/issues/15

**Closed by BlitzOffline** 2024-02-28 19:39 UTC

**Comment by hun1yy** [comment] 2024-02-29 13:20
he talking about items, but im talking about title minimessage support

**Comment by BlitzOffline** [comment] 2024-02-29 15:17
I have updated that issue to contain menu titles as well.
