### ISSUE TITLE
DM parsing PAPI placeholder before parsing Args placeholder

### ISSUE THREAD

**Issue by ElysiumSMP** [HelpChat/DeluxeMenus#78] opened 2024-03-25 20:25 UTC
**Version** 1.14.1-DEV-178
**Server Version** git-Purpur-2158 (MC: 1.20.4)

_(Issue opened on advice from `Prestley` in `HelpChat`)_
As described in the title. When trying to get DeluxeMenus to parse something like `%luckperms_meta_{player}_wealth%`, the placeholder breaks.

**Comment by BlitzOffline** [comment] 2024-03-25 21:19
Hello @ElysiumSMP, I have attempted to use the `%luckperms_meta_{player}_wealth%` placeholder myself but it does not seem to exist. Parsing it even with this command `/papi parse me %luckperms_meta_BlitzOffline_wealth%` returns nothing. The same as using your example inside a menu.

After taking a look at luckperms' wiki, I could not find any specification of the placeholder you were using. The only similar placeholder I found was `%luckperms_meta_wealth%`.

Of course, I have set a value for my `wealth` key using `/lp user BlitzOffline meta set wealth abc` and the placeholder I found on the wiki does work.

**Comment by BlitzOffline** [comment] 2024-03-26 17:15
After looking more over this issue, I have found the root cause. It is a side effect of our changes regarding parsing placeholders inside arguments.

We have previously made some changes to how arguments and placeholders are handled.
How it used to work:
- Parse Arguments
- Parse Placeholders

How it works now:
- Parse placeholders
- If enabled, parse placeholders inside arguments
- Parse arguments

These changes were made because we've realized that letting players parse arbitrary placeholders is bad. In my opinion, placeholders should be simple mapping operations without any side effects. Not everyone agrees or sticks by this rule. Some placeholders do things such as giving items to players, executing commands, etc. when they are parsed.

When I've made the changes, I have allowed menu designers to enable placeholder parsing inside arguments on a per-menu basis. I have missed that parsing arguments after parsing placeholders, does not allow menu designers to use arguments inside placeholders anymore.

We might have to revert these changes or add a new option that would allow menu designers to switch the order in which arguments and placeholders are parsed. If we were to add this new option, I think the option that parses placeholders that are inside arguments should be removed.

Feedback is very much appreciated!

**Comment by ElysiumSMP** [comment] 2024-03-29 10:22
Hi @BlitzOffline, thank you for your prompt response, and apologies for my relatively late response.

> Hello @ElysiumSMP, I have attempted to use the %luckperms_meta_{player}_wealth% placeholder myself but it does not seem to exist. Parsing it even with this command /papi parse me %luckperms_meta_BlitzOffline_wealth% returns nothing. The same as using your example inside a menu.

In response to the above, `%luckperms_meta_{player}_wealth%` is just an example meta key that utilises an `arg` within a placeholder. What I was using it for on my server, is to use `args` to call different data based on what the player specifies:
- For instance, I might have a command such as `/warp {args}` (which opens up a warp menu), and I'd use the placeholder `%luckperms_meta_warp_{args}_name%` to call the name of the specified warp.

> We might have to revert these changes or add a new option that would allow menu designers to switch the order in which arguments and placeholders are parsed. If we were to add this new option, I think the option that parses placeholders that are inside arguments should be removed.

Thank you for the detailed information. I personally do not really see as much utility in allowing `placeholders` to be parsed within `arguments` compared to the former, so I would prefer removing it. Then again I am biased haha.

**Comment by ElysiumSMP** [comment] 2024-04-02 07:29
Hi there, any updates here?

**Comment by ElysiumSMP** [comment] 2024-04-20 13:34
Bump

**Comment by BlitzOffline** [comment] 2024-05-25 21:29
@ElysiumSMP I have opened a PR to add a new option that would fix your issue (#99). If you don't want to wait until that is merged, you can test this build:
[DeluxeMenus-1.14.1-DEV-local-build.zip](https://github.com/HelpChat/DeluxeMenus/files/15445095/DeluxeMenus-1.14.1-DEV-local-build.zip)

**Closed** 2024-06-18 17:22 UTC
Labels: bug, enhancement
