### ISSUE TITLE
Add the plugin as a maven dependency

### ISSUE THREAD

**Issue by KendaFR** [HelpChat/DeluxeMenus#73] opened 2024-03-09 19:36 UTC
Hello, 

In order to improve the plugins, I would like to know if it was possible to integrate your plugin into Maven, in order to be able to use them internally?

thx

**Comment by BlitzOffline** [comment] 2024-03-09 21:03
Hello. I am unsure what exactly you mean by "integrating your plugin into Maven".

Do you want us to change to using Maven instead of Gradle?
Do you want us to create a remote Maven repository from where you can download the plugin?
Do you want us to create a remote Maven repository with an API that lets you integrate with the plugin?

There are so many things that could mean and I am really not sure which one it is.

**Comment by KendaFR** [comment] 2024-03-09 21:12
I would like a repository on Maven, in order to be able to use the plugin API, in my own plugins

**Comment by BlitzOffline** [comment] 2024-03-09 21:56
The plugin does not have an API yet. I am going to mark this as a duplicate of https://github.com/HelpChat/DeluxeMenus/issues/29

**Closed by BlitzOffline** 2024-03-09 21:56 UTC
